language: "ko-KR"
early_access: false

reviews:
  profile: "chill"
  review_depth: "medium"
  tone: "friendly"
  request_changes_workflow: true
  auto_approve: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true

ignored_paths:
  - node_modules/**
  - .github/**
